#服务端口
server:
  port: 8085
  servlet:
    context-path: /

#debug: true
#spring连接postgresql数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://118.24.166.159:5432/blog
    username: postgres
    password: r011698.
    driver-class-name: org.postgresql.Driver
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      # 配置获取连接等待超时的时间
      query-timeout: 6000
      maxWait: 2000
      #事务查询超时时间
      transaction-query-timeout: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,wall,config
      #日志显示sql
      logSlowSql: true

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml



